# Generated by Django 3.2 on 2021-05-01 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('conteudo', models.TextField(blank=True)),
                ('data_criacao', models.DateField(default='2021-05-01')),
                ('data_termino', models.DateField(default='2021-05-01')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listaApp.categoria')),
            ],
        ),
    ]
