# Generated by Django 3.2 on 2021-05-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='data_criacao',
            field=models.DateField(default='2021-05-03'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='data_termino',
            field=models.DateField(default='2021-05-03'),
        ),
    ]
