# Generated by Django 3.2 on 2021-05-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaApp', '0004_alter_lista_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='imge',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='data_criacao',
            field=models.DateField(default='2021-05-04'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='data_termino',
            field=models.DateField(default='2021-05-04'),
        ),
    ]
