# Generated by Django 3.2 on 2021-05-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listaApp', '0008_rename_img_imagemuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemuser',
            old_name='imge',
            new_name='imagem',
        ),
    ]
