# Generated by Django 3.2 on 2021-05-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaApp', '0010_alter_imagemuser_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemuser',
            name='imagem',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
