# Generated by Django 3.2 on 2021-05-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaApp', '0012_auto_20210505_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='data_criacao',
            field=models.DateField(default='2021-05-23'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='data_termino',
            field=models.DateField(default='2021-05-23'),
        ),
    ]
