# Generated by Django 3.2 on 2022-01-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaApp', '0013_auto_20210523_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='data_criacao',
            field=models.DateField(default='2022-01-19'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='data_termino',
            field=models.DateField(default='2022-01-19'),
        ),
    ]
